/**
 * Tool-contract generation shared by `pnpm contracts:update` and `test/contract-drift.test.ts`.
 *
 * The finalized tool registry (`ALL_TOOL_SPECS`) is the single authority. Every artifact that used
 * to restate it by hand is generated from it here:
 *
 * - `capabilities/union-manifest.json` canonical rows;
 * - `packages/mcp/test/plugin-contract.json`, the recorded plugin argument surface;
 * - The tool-count blocks in `README.md` and `packages/mcp/README.md`.
 *
 * Provenance that cannot be derived is read, never invented: upstream rows keep their recorded
 * source contracts, and service-local tools must be declared in `SERVICE_LOCAL_TOOLS` below. A
 * registry tool that fits no class stops generation instead of receiving a fabricated row.
 *
 * Plain Node needs `register-source.mjs` and `--experimental-transform-types` before importing this
 * module; `scripts/update-contracts.mjs` does both. Vitest transforms the TypeScript itself.
 */
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { format } from 'oxfmt';

import { ALL_TOOL_SPECS } from '../packages/mcp/src/tools/registry.ts';
import { SERVER_ONLY_TOOLS } from '../packages/mcp/src/tools/runtime-registry.ts';
import { derivePluginContract, diffContracts } from '../packages/mcp/test/plugin-contract.ts';
import { schemaContractJson } from '../packages/shared/src/capability-manifest.ts';
import { PORTAL_TOOL_NAMES } from '../packages/shared/src/portal.ts';
import { MIN_PLUGIN_VERSION } from '../packages/shared/src/version.ts';

export const SERVICE_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const UPDATE_COMMAND = 'pnpm contracts:update';

/** Source label of contracts this service defines itself (portal and service-local rows). */
export const SERVICE_SOURCE = 'super-figma-pipeline';

/**
 * Registry tools this service implements natively. They have no upstream source contract and are
 * not part of the portal contract, so each becomes a service-native manifest row whose only source
 * contract is the service's own input schema. Adding a tool here is a deliberate classification
 * step: generation refuses any registry tool that is not classified.
 */
export const SERVICE_LOCAL_TOOLS = Object.freeze([
  Object.freeze({
    // Bounded original-image chunks and exact-scale node exports for the portal capture plane.
    name: 'portal_capture_asset',
    sourceRef: 'packages/mcp/src/tools/portal-capture.ts#portal_capture_asset',
    availability: Object.freeze(['connected-plugin']),
    implementation: 'packages/plugin/src/handlers/portal-capture-asset.ts',
    test: 'packages/mcp/test/portal/desktop-capture.test.ts',
  }),
  Object.freeze({
    // Bounded tree, catalog and reference reads for the portal capture plane.
    name: 'portal_capture_read',
    sourceRef: 'packages/mcp/src/tools/portal-capture.ts#portal_capture_read',
    availability: Object.freeze(['connected-plugin']),
    implementation: 'packages/plugin/src/handlers/portal-capture-read.ts',
    test: 'packages/mcp/test/portal/desktop-capture.test.ts',
  }),
  Object.freeze({
    // Preimage-checked replacement of native node annotations; the upstreams only read them.
    name: 'set_annotations',
    sourceRef: 'packages/mcp/src/tools/set-annotations.ts',
    availability: Object.freeze(['connected-plugin']),
    implementation: 'packages/plugin/src/handlers/set-annotations.ts',
    test: 'packages/plugin/test/handlers/set-annotations.test.ts',
  }),
]);

export const SERVICE_LOCAL_TOOL_NAMES = Object.freeze(
  SERVICE_LOCAL_TOOLS.map(tool => tool.name).toSorted(),
);

export const ARTIFACT_PATHS = Object.freeze({
  manifest: 'capabilities/union-manifest.json',
  pluginContract: 'packages/mcp/test/plugin-contract.json',
  readmes: Object.freeze(['README.md', 'packages/mcp/README.md']),
});

export const TOOL_COUNT_BEGIN =
  '<!-- tool-count:begin (generated by pnpm contracts:update; do not edit) -->';
export const TOOL_COUNT_END = '<!-- tool-count:end -->';

/** A classification or structure problem that regeneration alone cannot resolve. */
export class ContractsError extends Error {
  constructor(problems) {
    super(
      [
        'Tool contracts cannot be generated from the registry:',
        ...problems.map(problem => `  - ${problem}`),
        `Resolve these, then run \`${UPDATE_COMMAND}\` from service/ and commit the result.`,
      ].join('\n'),
    );
    this.name = 'ContractsError';
    this.problems = problems;
  }
}

const sha256 = value => createHash('sha256').update(value).digest('hex');

/** Same bytes as scripts/update-target-contracts.mjs, which this generator supersedes. */
const targetContractHash = spec => sha256(schemaContractJson(spec.inputSchema, spec.resultSchema));

/** Same bytes as scripts/update-portal-contracts.mjs: the service's own input schema. */
const serviceSchemaHash = spec =>
  sha256(JSON.stringify(spec.inputSchema.toJSONSchema({ unrepresentable: 'any' })));

/** Upstream source labels, derived from the recorded source surfaces rather than restated. */
export const upstreamSources = manifest =>
  new Set([
    ...manifest.sourceSurfaces.lexicalTools.flatMap(row => row.sources),
    ...manifest.sourceSurfaces.figmoshaHelpers.map(row => row.source),
    ...manifest.sourceSurfaces.figmoshaCliParsers.map(row => row.source),
  ]);

/** A canonical row whose every source contract comes from a pinned upstream. */
export const isUpstreamRow = (row, sources) =>
  row.sourceContracts.length > 0 &&
  row.sourceContracts.every(contract => sources.has(contract.source));

// Row shape and special cases follow scripts/update-portal-contracts.mjs exactly.
const portalRow = spec => ({
  name: spec.name,
  sourceRefs: [`${SERVICE_SOURCE}:packages/shared/src/portal.ts#${spec.name}`],
  sourceContracts: [{ source: SERVICE_SOURCE, schemaHash: serviceSchemaHash(spec) }],
  targetContractHash: targetContractHash(spec),
  disposition: 'adapter',
  registration: 'advertised',
  availability: [
    'registered-workspace',
    'authenticated-owner',
    ...(spec.name === 'portal_validate' ? ['owner-native-profile-required', 'no-docker'] : []),
    ...(spec.name === 'portal_apply' ? ['complete-candidate-acceptance-required'] : []),
  ],
  investment: 'active',
  implementationStatus: 'implemented',
  implementation: 'packages/mcp/src/portal/coordinator.ts',
  test:
    spec.name === 'portal_validate' || spec.name === 'portal_apply'
      ? 'packages/mcp/test/portal/native-work.test.ts'
      : 'packages/mcp/test/portal/coordinator.test.ts',
  policyId: spec.policyId,
});

const serviceLocalRow = (spec, declaration) => ({
  name: spec.name,
  sourceRefs: [`${SERVICE_SOURCE}:${declaration.sourceRef}`],
  sourceContracts: [{ source: SERVICE_SOURCE, schemaHash: serviceSchemaHash(spec) }],
  targetContractHash: targetContractHash(spec),
  disposition: 'native',
  registration: 'advertised',
  availability: [...declaration.availability],
  investment: 'active',
  implementationStatus: 'implemented',
  implementation: declaration.implementation,
  test: declaration.test,
  policyId: spec.policyId,
});

/** Upstream rows keep their recorded provenance; only registry-derived fields are refreshed. */
const upstreamRow = (row, spec) => ({
  ...row,
  targetContractHash: targetContractHash(spec),
  policyId: spec.policyId,
});

/**
 * Rebuild the canonical rows from the registry. Existing rows keep their order; rows for newly
 * registered tools are appended in registry order. Source surfaces are never touched.
 */
export const buildUnionManifest = (current, specs = ALL_TOOL_SPECS) => {
  const sources = upstreamSources(current);
  const bySpec = new Map(specs.map(spec => [spec.name, spec]));
  const byRow = new Map(current.canonicalTools.map(row => [row.name, row]));
  const portal = new Set(PORTAL_TOOL_NAMES);
  const local = new Map(SERVICE_LOCAL_TOOLS.map(tool => [tool.name, tool]));
  const problems = [];

  for (const tool of SERVICE_LOCAL_TOOLS) {
    if (!bySpec.has(tool.name))
      problems.push(`SERVICE_LOCAL_TOOLS declares ${tool.name}, which is not registered.`);
  }
  const unclassified = [];
  for (const spec of specs) {
    const row = byRow.get(spec.name);
    const classes = [
      portal.has(spec.name) && 'portal contract',
      local.has(spec.name) && 'SERVICE_LOCAL_TOOLS',
      row !== undefined && isUpstreamRow(row, sources) && 'recorded upstream row',
    ].filter(Boolean);
    if (classes.length === 0) unclassified.push(spec.name);
    else if (classes.length > 1)
      problems.push(`${spec.name} is classified more than once (${classes.join(', ')}).`);
  }
  if (unclassified.length > 0)
    problems.push(
      `Registered tools with no recorded provenance: ${unclassified.join(', ')}. Record an ` +
        `upstream source row in ${ARTIFACT_PATHS.manifest}, add the tool to PORTAL_TOOL_NAMES, or ` +
        'declare it in SERVICE_LOCAL_TOOLS in scripts/contracts-lib.mjs.',
    );
  for (const row of current.canonicalTools) {
    if (!bySpec.has(row.name) && isUpstreamRow(row, sources))
      problems.push(
        `${row.name} has a recorded upstream row but is no longer registered. Remove the row and ` +
          'its source-surface mapping deliberately if the tool was retired.',
      );
  }
  if (problems.length > 0) throw new ContractsError(problems);

  const names = [
    ...current.canonicalTools.filter(row => bySpec.has(row.name)).map(row => row.name),
    ...specs.filter(spec => !byRow.has(spec.name)).map(spec => spec.name),
  ];
  const rowFor = name => {
    const spec = bySpec.get(name);
    if (portal.has(name)) return portalRow(spec);
    const declaration = local.get(name);
    if (declaration !== undefined) return serviceLocalRow(spec, declaration);
    return upstreamRow(byRow.get(name), spec);
  };
  return { ...current, canonicalTools: names.map(rowFor) };
};

/** The recorded plugin argument surface, stamped with the floor it was recorded against. */
export const buildPluginContract = () => ({
  minPluginVersion: MIN_PLUGIN_VERSION,
  tools: derivePluginContract(),
});

/** Counts behind the generated README line, all derived from the registry. */
export const toolCounts = (specs = ALL_TOOL_SPECS) => {
  const serverOnly = specs.filter(spec => SERVER_ONLY_TOOLS.has(spec.name)).length;
  return {
    total: specs.length,
    catalog: specs.length - SERVICE_LOCAL_TOOLS.length,
    serviceLocal: SERVICE_LOCAL_TOOL_NAMES,
    pluginHandlers: specs.length - serverOnly,
    serverOnly,
  };
};

export const toolCountLine = counts =>
  `**${counts.total} MCP tools**: ${counts.catalog} from the canonical capability catalog plus ` +
  `${counts.serviceLocal.length} service-local tools (` +
  `${counts.serviceLocal.map(name => `\`${name}\``).join(', ')}). ` +
  `${counts.pluginHandlers} have a Figma plugin handler and ${counts.serverOnly} run only on the ` +
  'server. Registration is not live design or target-portal acceptance.';

/** Replace the body of the single generated tool-count block. */
export const renderToolCountBlock = (text, path, line) => {
  const begin = text.indexOf(TOOL_COUNT_BEGIN);
  const end = text.indexOf(TOOL_COUNT_END);
  if (
    begin === -1 ||
    end < begin ||
    text.indexOf(TOOL_COUNT_BEGIN, begin + 1) !== -1 ||
    text.indexOf(TOOL_COUNT_END, end + 1) !== -1
  )
    throw new ContractsError([
      `${path} needs exactly one "${TOOL_COUNT_BEGIN}" ... "${TOOL_COUNT_END}" block.`,
    ]);
  return `${text.slice(0, begin + TOOL_COUNT_BEGIN.length)}\n${line}\n${text.slice(end)}`;
};

let formatOptions;
const formatterOptions = async root => {
  if (formatOptions === undefined) {
    const {
      $schema: _schema,
      ignorePatterns: _ignored,
      ...options
    } = JSON.parse(await readFile(join(root, '.oxfmtrc.json'), 'utf8'));
    formatOptions = options;
  }
  return formatOptions;
};

/** Format exactly as `pnpm format` would, so a regenerated file is also format-clean. */
const formatted = async (root, path, text) => {
  const result = await format(path, text, await formatterOptions(root));
  if (result.errors.length > 0)
    throw new Error(`${path}: ${result.errors.map(error => error.message).join('; ')}`);
  return result.code;
};

const readOptional = async path => {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (error?.code === 'ENOENT') return null;
    throw error;
  }
};

/** Describe what changed between two manifests by row name. */
const manifestChanges = (currentText, nextManifest) => {
  let current;
  try {
    current = JSON.parse(currentText);
  } catch {
    return ['unparseable'];
  }
  const before = new Map(current.canonicalTools.map(row => [row.name, JSON.stringify(row)]));
  const after = new Map(nextManifest.canonicalTools.map(row => [row.name, JSON.stringify(row)]));
  const added = [...after.keys()].filter(name => !before.has(name));
  const removed = [...before.keys()].filter(name => !after.has(name));
  const changed = [...after.keys()].filter(
    name => before.has(name) && before.get(name) !== after.get(name),
  );
  return [
    ...(added.length > 0 ? [`rows added: ${added.join(', ')}`] : []),
    ...(removed.length > 0 ? [`rows removed: ${removed.join(', ')}`] : []),
    ...(changed.length > 0 ? [`rows changed: ${changed.join(', ')}`] : []),
  ];
};

/** Classify plugin-surface drift the way the original plugin-contract gate did. */
export const pluginDriftLines = (currentText, next) => {
  let recorded;
  try {
    recorded = JSON.parse(currentText);
  } catch {
    return ['unparseable'];
  }
  const drift = diffContracts(recorded.tools ?? {}, next.tools);
  const lines = [];
  if (drift.addedArgs.length > 0)
    lines.push(
      `SILENT on older plugins, ${drift.addedArgs.length} new argument(s) on existing tools: ` +
        `${drift.addedArgs.join(', ')}. A handler that predates them drops them and still ` +
        `answers { ok: true }; raise MIN_PLUGIN_VERSION (now ${MIN_PLUGIN_VERSION}) to the ` +
        'version that ships them.',
    );
  if (drift.removedArgs.length > 0 || drift.removedTools.length > 0)
    lines.push(
      `REMOVED, a plugin still sending or expecting these is now wrong: ${[
        ...drift.removedArgs,
        ...drift.removedTools.map(tool => `${tool} (whole tool)`),
      ].join(', ')}. Raise MIN_PLUGIN_VERSION.`,
    );
  if (drift.addedTools.length > 0)
    lines.push(
      `LOUD on older plugins, new tools: ${drift.addedTools.join(', ')}. An older plugin ` +
        'answers METHOD_NOT_FOUND, which is visible, so this class alone does not require ' +
        'raising the floor.',
    );
  if (recorded.minPluginVersion !== next.minPluginVersion)
    lines.push(
      `recorded floor ${recorded.minPluginVersion} differs from the current floor ` +
        `${next.minPluginVersion}.`,
    );
  return lines.length > 0 ? lines : ['formatting or ordering only'];
};

/**
 * Generate every registry-derived artifact. Returns each artifact's current and generated text plus
 * a human-readable description of any difference; writes nothing.
 */
export const generateContracts = async ({ root = SERVICE_ROOT } = {}) => {
  const [currentManifestText, currentPluginText, ...currentReadmes] = await Promise.all([
    readFile(join(root, ARTIFACT_PATHS.manifest), 'utf8'),
    readOptional(join(root, ARTIFACT_PATHS.pluginContract)),
    ...ARTIFACT_PATHS.readmes.map(path => readFile(join(root, path), 'utf8')),
  ]);
  const nextManifest = buildUnionManifest(JSON.parse(currentManifestText));
  const nextPlugin = buildPluginContract();
  const line = toolCountLine(toolCounts());

  const drafts = [
    {
      path: ARTIFACT_PATHS.manifest,
      current: currentManifestText,
      generated: `${JSON.stringify(nextManifest, null, 2)}\n`,
      describe: () => manifestChanges(currentManifestText, nextManifest),
    },
    {
      path: ARTIFACT_PATHS.pluginContract,
      current: currentPluginText,
      generated: `${JSON.stringify(nextPlugin, null, 2)}\n`,
      describe: () =>
        currentPluginText === null
          ? ['missing (it is committed; restore it from git before regenerating)']
          : pluginDriftLines(currentPluginText, nextPlugin),
    },
    ...ARTIFACT_PATHS.readmes.map((path, index) => ({
      path,
      current: currentReadmes[index],
      generated: renderToolCountBlock(currentReadmes[index], path, line),
      describe: () => ['tool-count block'],
    })),
  ];
  const texts = await Promise.all(
    drafts.map(draft => formatted(root, draft.path, draft.generated)),
  );
  return drafts.map((draft, index) => {
    const next = texts[index];
    return {
      path: draft.path,
      current: draft.current,
      next,
      stale: draft.current !== next,
      describe: draft.describe,
    };
  });
};

/** The drift report for stale artifacts, or '' when every artifact matches the registry. */
export const driftReport = artifacts => {
  const stale = artifacts.filter(artifact => artifact.stale);
  if (stale.length === 0) return '';
  const lines = ['Generated tool contracts are out of date with the tool registry:'];
  for (const artifact of stale) {
    lines.push(`  ${artifact.path}`);
    for (const detail of artifact.describe()) lines.push(`    - ${detail}`);
  }
  lines.push(`Run \`${UPDATE_COMMAND}\` from service/, review the diff, and commit it.`);
  return lines.join('\n');
};
